name: Front-end

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: ubuntu-latest
    outputs:
      tag_id: latest

    steps:
    - uses: actions/checkout@v4
    - name: Get timestamp # get the date of the build
      id: date
      run: echo "date=$(TZ=':America/Bogota' date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sofiat2024/backend-def:latest
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image to Dockerhub
      run: docker push sofiat2024/backend-def:latest

 deployapp:
  
      runs-on: ubuntu-latest
      needs: [ build ]
  
      steps:
      - uses: actions/checkout@v4
      - name: Run Terraform
        run: |
              set -e
              terraform init -input=false
              terraform apply -input=false -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
